source 'https://github.com/YuvarajIcon/PodSpecRepo.git'
use_frameworks!
platform :ios, '13.0'

target 'LoadableImageView_Example' do
  pod 'Downloader'
  pod 'HelpfulExtensions'
  pod 'LoadableImageView', :path => '../'
end
